packages:
  - playground
  - docs
  - packages/*
  - examples/*

catalogs:
  cli:
    '@antfu/eslint-config': ^4.10.1
    eslint: ^9.22.0
    etherlib-generator: ^0.0.9
    lint-staged: ^15.5.0
    nip: ^1.1.0
    simple-git-hooks: ^2.11.1
    tsx: ^4.19.3
    typescript: ^5.8.2
  contracts:
    '@openzeppelin/contracts': ^5.3.0
    '@openzeppelin/contracts-upgradeable': ^5.3.0
    solady: ^0.1.19
  inlined:
    '@nomicfoundation/hardhat-ignition': 3.0.0-next.13
    '@nomicfoundation/hardhat-ignition-viem': 3.0.0-next.13
    '@nomicfoundation/hardhat-toolbox-viem': 4.0.0-next.13
    '@nomicfoundation/hardhat-viem': 3.0.0-next.13
    hardhat: 3.0.0-next.13
  tooling:
    ethers: ^6.14.3
    forge-std: github:foundry-rs/forge-std#v1.9.4
    viem: ^2.29.2
  types:
    '@types/node': ^22.13.10
  utils:
    '@hairy/utils': ^1.30.0
    nanoid: ^5.1.5
onlyBuiltDependencies:
  - simple-git-hooks
